### ISSUE TITLE
Font Panic

### ISSUE THREAD

**Issue by DrewRidley** [mvlabat/bevy_egui#106]
```
2022-06-01T20:00:59.156772Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX 6900 XT", vendor: 4098, device: 29631, device_type: DiscreteGpu, backend: Vulkan }
thread 'Compute Task Pool (2)' panicked at 'No fonts available until first call to Context::run()', C:\Users\drewr\.cargo\registry\src\github.com-1ecc6299db9ec823\egui-0.18.1\src\context.rs:535:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'task has failed', C:\Users\drewr\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.2.0\src\task.rs:425:45
error: process didn't exit successfully: `target\debug\spacebandits.exe` (exit code: 101)
PS C:\Users\drewr\Documents\Projects\spacebandits>
```

**Comment by mvlabat** [comment]
I believe you're trying to render something before the context is initialized. Are your systems added to the `CoreStage::PreUpdate` stage by any chance? If so, you should run your system after `EguiSystem::BeginFrame`, or you can move your system to the `CoreStage::Update` stage.

**Comment by mvlabat** [comment]
I'll close this for now as I believe there's no issue on the `bevy_egui` end. But let me know if you're still facing problems.
